### ISSUE TITLE
Bootcamp Feedback TODO

### ISSUE THREAD

**Issue by danilolab** [Julia-Mazaia/SAP011-social-network#1]
- [ ] Escrever os testes unitários, mocks e testes assíncronos
 - [ ] Estudar as bibliotecas RxJS e MomentJS, para entender melhor assincronicidade e tratamento de datas
 - [ ] Criar projetos pessoais, com base em problemas reais e publicar no git para demonstrar seus conhecimentos, dicas de ideias: https://github.com/florinpop17/app-ideas?tab=readme-ov-file#tier-1-beginner-projects
 - [ ] Recomendação de sites: https://www.hackerrank.com/, https://leetcode.com/ e https://www.codewars.com/
 - [ ] Refazer alguns exercícios da GYM focados em design
 - [ ] Implementar a página de exibição dos feeds, bem como a manipulação dos feeds (alterar e excluir)
 - [ ] Fazer a integração com o Firebase Firestore: https://firebase.google.com/docs/firestore?hl=pt-br
 - [ ] Entenda mais os conceitos base das técnicas utilizadas: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide
